name: BlazinFeed
version: 1.2.1
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
description: Feeding System for PocketMine-MP
author: iiFlamiinBlaze
main: iiFlamiinBlaze\BlazinFeed\BlazinFeed
commands:
 feed:
  description: Commands that feeds the player
  permission: feed.command
  usage: "/feed <player>"
permission:
 feed.command:
  default: op